import argparse
import time
import torch
import cv2
import numpy as np
from pathlib import Path
from typing import List, Dict, Any

# Local imports
from yolo_one.inference import YoloOneInference

def detect(args: argparse.Namespace):
    """Main detection function."""
    
    # 1. Initialize the inference engine
    print("Initializing YOLO-One inference engine...")
    if not args.weights or not Path(args.weights).exists():
        raise FileNotFoundError(f"Weights file not found or not specified: {args.weights}")
        
    inference_engine = YoloOneInference(
        model_path=args.weights,
        device=args.device,
        confidence_threshold=args.conf,
        nms_threshold=args.iou,
        input_size=args.input_size,
        model_size=args.model_size,
        use_moe=args.use_moe
    )
    print("Inference engine ready.")

    # 2. Load image and run prediction
    print(f"Processing image: {args.source}")
    original_image = cv2.imread(str(args.source))
    if original_image is None:
        raise FileNotFoundError(f"Could not read image at: {args.source}")

    results = inference_engine.predict_image(
        image=original_image, # Pass the numpy array
        visualize=True # Request the visualization from the engine
    )
    inference_time = results.get('inference_time', 0)
    fps = 1.0 / inference_time if inference_time > 0 else 0
    print(f"Found {results['num_detections']} objects in {results['total_time']*1000:.2f}ms (Inference: {inference_time*1000:.2f}ms, FPS: {fps:.1f}).")

    # 3. Use the results
    detections = results['detections']

    # Get and save the visualization generated by the engine
    output_image = results['visualization']
    output_path = Path(args.output_dir) / args.source.name
    output_path.parent.mkdir(parents=True, exist_ok=True)
    cv2.imwrite(str(output_path), output_image)
    print(f"Output image saved to: {output_path}")

    print("\nDetection complete. You can view the output image in the specified directory.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="YOLO-One Detection Script")
    parser.add_argument('--weights', type=str, default=None, help='Path to model weights file.')
    parser.add_argument('--source', type=Path, required=True, help='Path to input image.')
    parser.add_argument('--model-size', type=str, default='nano', choices=['nano', 'small', 'medium', 'large'], help='Model size.')
    parser.add_argument('--use-moe', default=True, action='store_true', help='Specify if the model was trained with Mixture of Experts.')
    parser.add_argument('--input-size', type=int, default=640, help='Model input size.')
    parser.add_argument('--conf', type=float, default=0.05, help='Confidence threshold.')
    parser.add_argument('--iou', type=float, default=0.05, help='IoU threshold for NMS.')
    parser.add_argument('--device', type=str, default=None, help='Device to use (e.g., cpu, cuda, cuda:0).')
    parser.add_argument('--output-dir', type=str, default='./runs/detect', help='Directory to save output images.')

    args = parser.parse_args()

    detect(args)